### ISSUE TITLE
change exception handling in buildOpti test call

### ISSUE THREAD

**Issue by vpericoli** [jonathancurrie/OPTI#1]
Hi, I would like to propose a change to the checkOpti subfunction in buildOpti.m

If the objective function contains an error in execution, checkOpti detects it on [line 851](https://github.com/jonathancurrie/OPTI/blob/master/%40opti/buildOpti.m#L851). 

```
catch ME
    error('OPTI detected an error running a test objective call. Please correct the error below and try again:\n\n%s\n',ME.message);
end
```

However, the code generates a new exception, and simply prints the string description of the original exception. The problem is that the description does not contain any information about where the original error was generated. For complicated objective functions, it can be difficult to locate which function call or line the original exception belongs to.

Therefore, I propose that checkOpti re-throw the original exception. A standard print or similar can be used to alert the user that OPTI detected an error. Something like:

```
catch ME
    fprintf('\nOPTI detected an error running a test objective call. Please correct the error below and try again:\n\n%s\n\n',ME.message);
    rethrow(ME);
end
```

This way, MATLAB will throw the original exception with all info (including functions and lines with hyperlinks).

**Comment by jonathancurrie** [comment]
Excellent suggestion, I will make the change this evening.

**Comment by jonathancurrie** [comment]
Updated in master now. Please confirm if this fixes the issue as per your expectation.

**Comment by vpericoli** [comment]
Yes, it looks great!

Closing the issue.
