### ISSUE TITLE
Using multisolve()

### ISSUE THREAD

**Issue by shyamsrinivasan** [jonathancurrie/OPTI#2]
hi jonathan

I know that you have included a description for using a multi start solver with opti here : https://www.inverseproblem.co.nz/OPTI/index.php/Advanced/MultiSolve

However, using the option (with MATLAB) returns an error saying the command/function does not exist. I have checked your class definitions and its methods and did find the multisolve() method there. So, my question is, why is it still not working?

I have been using opti for quite sometime with some other solver for nlps (nlopt, nomad, scip and baron). I would very like to test this one out as well and see the difference in the solutions.

Thank you

**Comment by jonathancurrie** [comment]
Hi, I'm not sure what the problem is - this should work fine if OPTI is
installed correctly. Try reinstalling it using the supplied install script.
If the problem persists, please post the error you are getting.

Jonathan

On Sun, May 28, 2017 at 10:09 AM, Shyam Srinivasan <notifications@github.com

**Comment by shyamsrinivasan** [comment]
Hi Jonathan

Looks like it was installation issue. I wasn't sure after I did the re-install the first time and added folder paths to Matlab manually. 
Thank you for the suggestion.
