### ISSUE TITLE
Let user compile from source

### ISSUE THREAD

**Issue by yasirroni** [jonathancurrie/OPTI#20]
Hi @jonathancurrie. Since this project is no longer supported, can you release all the codes and let community maintain it? I'm interested to make a fork that support mac and linux devices.

As mentioned in this issue https://github.com/jonathancurrie/OPTI/issues/5, you only support windows. Can you share with us the source to build the mex file to support other OS?

Thank you.

**Comment by jonathancurrie** [comment]
Hi there, all source for OPTI is already provided in the repository - see [here](https://github.com/jonathancurrie/OPTI/tree/master/Solvers/Source).

Thanks,
Jonathan

**Comment by Cz1544252489** [comment]
Hi @yasirroni, I face the same problem trying to use this resp. on macOS. May I ask if you finish it? and how can I try this?
Thanks a lot.

**Comment by yasirroni** [comment]
> Hi [@yasirroni](https://github.com/yasirroni), I face the same problem trying to use this resp. on macOS. May I ask if you finish it? and how can I try this? Thanks a lot.

Hi @Cz1544252489, I ended up using SCIP because I'm stuck installing this on M1.

**Comment by Cz1544252489** [comment]
> > Hi [@yasirroni](https://github.com/yasirroni), I face the same problem trying to use this resp. on macOS. May I ask if you finish it? and how can I try this? Thanks a lot.
> 
> Hi [@Cz1544252489](https://github.com/Cz1544252489), I ended up using SCIP because I'm stuck installing this on M1.

I see, thanks for your reply.
