### ISSUE TITLE
Reference to non-existent field

### ISSUE THREAD

**Issue by bronsco** [jonathancurrie/OPTI#4]
Hi,

I have just found a small problem in the function convNlopt regarding a non-existent field 'algorithm'. This occurs for the expression ([line 77](https://github.com/jonathancurrie/OPTI/blob/716c6c88c314bd4c482fbdd9fe475775f8d1448f/Utilities/opti/convNlopt.m#L77), [line 91](https://github.com/jonathancurrie/OPTI/blob/716c6c88c314bd4c482fbdd9fe475775f8d1448f/Utilities/opti/convNlopt.m#L91), [line 105](https://github.com/jonathancurrie/OPTI/blob/716c6c88c314bd4c482fbdd9fe475775f8d1448f/Utilities/opti/convNlopt.m#L105))
```upper(nloptSolver(mprob.algorithm))```
which has to be
```upper(nloptSolver(mprob.options.algorithm))```
instead.

Best regards,
Ronnie

**Comment by jonathancurrie** [comment]
Fixed in latest master, thanks for reporting this!
