### ISSUE TITLE
Installation for Linux

### ISSUE THREAD

**Issue by berndporr** [jonathancurrie/OPTI#5]
>> opti_Install

------------------------------------------------
  INSTALLING OPTI TOOLBOX ver 2.27

- Checking MATLAB version and operating system...
Error using opti_Install>matlabVerCheck (line 214)
OPTI Toolbox is compiled only for Windows systems - sorry!

Error in opti_Install (line 38)
matlabVerCheck();

It's nowhere mentioned in the README that it's just for Window. 

Any chance that I can also install that under Linux?

And if not it might be very, very nice to tell that the "victim" before he/she embarks on it trying to install it under Linux.

**Comment by jonathancurrie** [comment]
Apologies, Github is only the distribution mechanism for the project - the Wiki is here:
https://inverseproblem.co.nz/OPTI/index.php/Main/WhatIsOPTI?

**Comment by nahueldeniz** [comment]
you like free stuff but it's available only for windows??? you are the best joker...
