### ISSUE TITLE
Can't download The OPTI Toolbox Academic Extension 

### ISSUE THREAD

**Issue by Ariostgx** [jonathancurrie/OPTI#7]
When I click the "download" button on the following page:
(https://www.inverseproblem.co.nz/OPTI/index.php/DL/Academic)
I get the message:

> Inverse Problem Form Error
Unfortunately you have not completed all the required fields. Please go back to the previous page and complete all fields.
The following fields were not completed or had errors:
ReCaptcha

How can I fix this problem?

**Comment by jonathancurrie** [comment]
Please complete the ReCaptcha (e.g. "I am not a robot" tickbox) to complete the download.
