### ISSUE TITLE
'bonmin' option error

### ISSUE THREAD

**Issue by woodwm** [jonathancurrie/OPTI#8]
Hello, I find an error in the `bonmin` solver by using `yalmip` and Johan said that is maybe a error in the `opti`.

The matlab code is [test_if.txt](https://github.com/jonathancurrie/OPTI/files/2302526/test_if.txt). It is an example of yalmip to model if-else.

OPTI version: v2.28
YALMIP version: '20180817'
Matlab version: r2018a
Error message:
```
Error using bonmin
*** Error using Bonmin Matlab interface: ***
You have specified a nonexistent BONMIN/IPOPT option
("pardiso_redo_symbolic_fact_only_if_inertia_wrong").

Error in callbonmin (line 126)
[xout,info] = bonmin(model.x0,funcs,options);
Error in solvesdp (line 350)
    eval(['output = ' solver.call '(interfacedata);']);
Error in optimize (line 31)
[varargout{1:nargout}] = solvesdp(varargin{:});
Error in test_if (line 34)
optimize(Model,Objective,options)
```

**Comment by jonathancurrie** [comment]
Hi, unfortunately I have not built BONMIN with PARDISO in OPTI, based on the large download size required. Therefore this option does not exist in the interface.

**Comment by JiweiTian** [comment]
@woodwm I have encountered the same problem, have you solved it?

Error using bonmin
*** Error using Bonmin Matlab interface: ***
You have specified a nonexistent BONMIN/IPOPT option
("pardiso_redo_symbolic_fact_only_if_inertia_wrong").

Error in callbonmin (line 126)
[xout,info] = bonmin(model.x0,funcs,options);
Error in solvesdp (line 350)
    eval(['output = ' solver.call '(interfacedata);']);
Error in optimize (line 31)
[varargout{1:nargout}] = solvesdp(varargin{:});
Error in test_if (line 34)
optimize(Model,Objective,options)
